### ISSUE TITLE
Is this on Maven Central?

### ISSUE THREAD

**Issue by bnjmnt4n** [berndporr/iirj#1]
I can't seem to install it from Mven Central.

**Comment by berndporr** [comment]
There are discussions to get this into commons math so I'm holding it off for now. Also it's still just RC2 so needs a bit more testing.

**Comment by hmf** [comment]
Any update on this issue?

**Comment by berndporr** [comment]
Should be now on maven central:

compile group: 'uk.me.berndporr', name:'iirj', version: '1.0'

<dependency>
  <groupId>uk.me.berndporr</groupId>
  <artifactId>iirj</artifactId>
  <version>1.0</version>
</dependency>

Let me know if that works for you.

**Comment by hmf** [comment]
@berndporr Seems to be working. Accessed library using SBT (Ivy). 
Thank you.
