### ISSUE TITLE
Some help converting code from Matlab

### ISSUE THREAD

**Issue by mstevens83** [berndporr/iirj#11]
Hello,
Are you familiar with Matlab by any change?
If so, would you mind helping me convert a few lines of Matlab code to Java using IIRJ.
This is the code in question:
```matlab
tempo = 100
fs = 44100

% Butterworth 3rd order bandpass
[b_but, a_but] = butter(3, [20 140+tempo]/(0.5*fs), 'bandpass');
filtered_pulse = filter(b_but, a_but, pulse);

% Peaking filter
[b_peak, a_peak] = iirpeak(110/(fs/2), 120/(0.5*fs));
filtered_pulse = filter(b_peak, a_peak, filtered_pulse);
```

For the 1st part I already have this:
```java
private int fs = 44100;
private int temp = 100;

public double[] applyBandpass(double[] pulse) {
	double filteredPulse = new double[pulse.length];
	Butterworth butter = new Butterworth();
	butter.bandPass(3, 44100, ?centerFrequency?, ?widthFrequency?);
	for(int i = 0; i < pulse.length; i++)
		filteredPulse[i] = filter.filter(pulse[i]);
	return filteredPulse;
}
```
I'm not sure how to compute the `centerFrequency` and `widthFrequency`.
In the Matlab code there is just `[20 140+tempo]/(0.5*fs)`, and sample rate is not passed separately.

For the 2nd part I don't have any java code yet because I'm not sure which class of your library to use for the `iirpeak()` filter.

Thanks in advance for any help.

**Comment by berndporr** [comment]
I've got no idea what the peaking filter does but if you want to imitate matlab I'd use a cascade of a low and highpass instead. Gives you the same order.

**Comment by mstevens83** [comment]
According to matlab docs `iirpeak()` is a second-order digital peaking filter.

**Comment by berndporr** [comment]
Basically a bandpass filter with a specified width so the bandpass which iir1 offers. I guess you need to figure out the gain at resonance. Sorry. I leave that to you to calc that. See the MATLAB ref. The gain of the iir1 bandpass is one in the passband.On 14 Jun 2018 12:10 pm, Matthias Stevens <notifications@github.com> wrote:According to matlab docs iirpeak() is a second-order digital peaking filter.
