### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by mstevens83** [berndporr/iirj#12]
Hello, I think you may have forgotten to comment out this debug print statement:
https://github.com/berndporr/iirj/blob/30f1c1222d3e7a320dc106468d2e384ded9e6d28/src/main/java/uk/me/berndporr/iirj/LayoutBase.java#L75

**Comment by berndporr** [comment]
Oh yes. I've just removed this line. This was indeed still in there from the debug phase. Thanks for spotting it. Very much appreciated.

**Comment by berndporr** [comment]
should be also now a new version on maven called 1.1.
