### ISSUE TITLE
Applying butterworth bandpass filter on a wav file

### ISSUE THREAD

**Issue by DIPLO22** [berndporr/iirj#17]
I want to filter an already saved audio in the form of wav file. I know that the filter needs a double array for filtering. So, I have read the audio in a byte array and then converted that byte array to a double array. After applying the filter on the double array with a for loop, I have converted the double array to bytes and then wav file again but the resulting audio file is choppy and doesn't look filtered in a audio spectrum analyzer.

I can provide the code if anyone interested!

**Comment by berndporr** [comment]
Sorry but I won't debug your code. If you discover a bug in the iir code then submit a pull request. If you work on arrays then I'd recommend the DSPfilters library. See bottom of the README.
