### ISSUE TITLE
Changing target Frequency while feeding in new Samples

### ISSUE THREAD

**Issue by bsondermann** [berndporr/iirj#19]
Hi!
I have a .csv file containing target frequencies that need to be filtered out with a band stop filter.
These frequencies change over time. Is it possible to do that? Because I tried it the obvious way by calling the butterworth.bandStop function with the new frequency before feeding the next sample, but that doesn't seem to work.
Thanks
Bastian

**Comment by berndporr** [comment]
Hi, you mean you call `setup()` after every sample? That won't work as iir filters need to settle for roughly 1/cutoff_freq. You could call `setup()` once in a while but there will always be a settling time.
/Bernd

**Comment by bsondermann** [comment]
Oh yeah thanks! I created 100 Bandstop filters spread over the spectrum and select the right one! It isn't perfect because sometimes is crackles when it switches between the filters, but its enough for my purpose. (I guess I could fix this by fading between them)
Thanks again!
Bastian

**Comment by berndporr** [comment]
Great! Glad it worked.
