### ISSUE TITLE
A querstion about HighPass

### ISSUE THREAD

**Issue by GiottoLee** [berndporr/iirj#22]
I'm trying to transform a java UDF from python code.  In python, it use scipy.signal as highpass filter,  i'm searching a lot time and found this project. But i can't get the same result, so i wanna know what's difference between Butterworth.highpass() and scipy.signal.butter?

**Comment by berndporr** [comment]
scipy.signal.butter gives you just coefficients but it's not filtering anything. Butterworth.highpass() is class which performs causal filtering with its filter() function. You are comparing apples with pears. Sorry, just saying "can't get the same result" is ill posed and without a test-case has no value as it's just a vague statement. So I'm closing it now.
