### ISSUE TITLE
Add Support for Cauer / Elliptic Filter

### ISSUE THREAD

**Issue by anleu** [berndporr/iirj#26]
It would be beneficial to include support for the Cauer / Elliptic filter. A potential reference for the implementation can be found in Vinnie Falco's work at  https://github.com/vinniefalco/DSPFilters/blob/master/shared/DSPFilters/source/Elliptic.cpp

I plan to implement this in Q4/2023.

**Comment by berndporr** [comment]
Some history here: the IIRJ library is a JAVA port of the IIR1 C++ library which is again a continuation of Vinnie Falco's DSPFilters. Any code based on the solver (Bessel, Elliptic, etc) is experimental and contains hacks. For that reason it's been removed. See also my comment about Bessel. The DSPFilters hasn't heen maintained for about a decade. Sorry, but that's a complete showstopper.
