### ISSUE TITLE
Issue with Odd-Order Highpass Filters

### ISSUE THREAD

**Issue by anleu** [berndporr/iirj#27]
After introducing new tests, it was observed that highpass filters of odd order produce incorrect results. This issue has already been reported in the original library, as seen in [this issue](https://github.com/vinniefalco/DSPFilters/issues/29).

The proposed fix appears to be effective. Both [tbrunsch](https://github.com/tbrunsch) and I have tested the fix, and it seems to work without introducing any other issues. Additionally, upon reviewing the code, we've verified that the changes exclusively affect the highpass filter and do so correctly.

We will be submitting a PR that includes both the unit tests and the fix for this problem.

**Comment by berndporr** [comment]
![id-0001](https://github.com/berndporr/iirj/assets/1679394/48276bce-0afa-49c1-a6aa-6427a0720fc9)
thanks. Indeed. Pole and zero should end up in the same coefficient as the math is the same of both numerator and denominator.
