### ISSUE TITLE
Noob question on high pass and notch filter

### ISSUE THREAD

**Issue by rakadambi** [berndporr/iirj#30]
Hi there,

I am learning this and this works great. I want to apply high pass and then notch filter of 50.Hz This is a newbie question

So, do I do this?

Butterworth butterworth = new Butterworth();
butterworth.highPass(4, 250, 1);
butterworth.bandStop(4, 250, 50, 0);

and then

butterworth.filter(myVal)

Thank you

**Comment by berndporr** [comment]
Yes but you can't have a bandwidth of 0 for a notch. Perhaps start with 5Hz bandwidth and then make it smaller. Damping at 50Hz will get worse the more narrow it is. Sooo there is the classical tradeoff as always in DSP!

**Comment by rakadambi** [comment]
Thank you very much. Fantastic library.

I'll close the issue now
