### ISSUE TITLE
About the filter initial conditions 

### ISSUE THREAD

**Issue by qiuyudong** [berndporr/iirj#7]
Hello,is a great library. and now I need to implement   " y = filter(b,a,x,zi)"  like this in matlab,Do you know how to do it or have any library exists.Thank you very much
[https://cn.mathworks.com/help/matlab/ref/filter.html#bt_vs4t-2_1](url)

**Comment by qiuyudong** [comment]
It was just about how to use initial conditions in your library

**Comment by berndporr** [comment]
The MATLAB filter command and its design commands such as butter are generating direct N-th order IIR filters. This is pretty dangerous stability-wise and also precision-wise. Instead this IIR library generates directly from the complex conjugate pole/zero pairs 2nd order IIR coefficients to avoid both stability and rounding errors.
Having said that if you want to set the initial conditions of the IIR filter you can do that by directly setting the coefficients of the biqads. See `Cascade.java`:
```
/**
 * 
 * The mother of all filters. It contains the coefficients of all
 * filter stages as a sequence of 2nd order filters and the states
 * of the 2nd order filters which also imply if it's direct form I or II
 *
 */
public class Cascade {

        // coefficients
        private Biquad[] m_biquads;
```
which in turn then can have a direct form I or direct form II structure which are again classes.
`m_v1` and `m_v2` are for example the state variables for the direct Form II which you can set to your convenience.

**Comment by qiuyudong** [comment]
thank you . it helps me a lot
